[Enhanced function] Issue #1046
dotnet/TorchSharp pull request #1060
Opened 2023-08-09 09:38 UTC by ChengYen-Tang

https://github.com/dotnet/TorchSharp/issues/1046

2023-08-09 14:46 UTC, NiklasGustafsson requested changes

2023-08-09 14:46 UTC, NiklasGustafsson commented on src/TorchSharp/Scalar.cs
> +#if NET5_0_OR_GREATER
We no longer support .NET 5

2023-08-09 14:46 UTC, NiklasGustafsson commented on src/TorchSharp/Tensor/Tensor.Factories.cs
> +#if NET5_0_OR_GREATER
See previous comment about .NET 5

2023-08-09 14:47 UTC, NiklasGustafsson commented
Awesome! Thanks for the help. Only comment is that we no longer support .NET 5, so is should probably be `if NET5_OR_GREATER`

2023-08-09 15:12 UTC, ChengYen-Tang commented
Ok, I will fix it tomorrow, I am a little tired today, good night.

2023-08-10 01:46 UTC, NiklasGustafsson approved these changes

2023-08-10 20:50 UTC, merged