Implementation of jacobian method, based on PyTorch implementation
dotnet/TorchSharp pull request #1195
Opened 2023-12-23 11:22 UTC by roelofsmn

Initial implementation of the jacobian method, based on https://pytorch.org/docs/stable/_modules/torch/autograd/functional.html#jacobian .
Resolves #1149.

Omits several options from the PyTorch implementation, such as `create_graph`, `strict`, `vectorize` and `strategy`.
It behaves as if `create_graph=False`, `strict=False`, `vectorize=False` and `strategy="reverse-mode"`.

I added an example of usage in the documentation of the method itself.

@NiklasGustafsson

2023-12-23 11:25 UTC, roelofsmn commented
@dotnet-policy-service agree

2024-01-02 16:02 UTC, NiklasGustafsson commented
@roelofsmn -- thanks for the PR! I've been out on Christmas break, but I'll take a look at this later today.

2024-01-02 16:12 UTC, NiklasGustafsson requested changes
Also, please add a few unit tests.

2024-01-02 16:12 UTC, NiklasGustafsson commented on src/TorchSharp/Functional.cs
> +                        inputs = _grad_preprocess(need_graph: true, inputs);
It may be worth having a dispose scope around the body of this method.

2024-01-02 16:12 UTC, NiklasGustafsson commented on src/TorchSharp/Functional.cs
> +                public static IEnumerable<Tensor> jacobian(Func<Tensor[], Tensor[]> function, params Tensor[] inputs)
This is very general, but consider whether there are other overloads that would be useful here.

2024-01-02 16:40 UTC, roelofsmn commented
Thanks for the feedback! Currently, I am away, but I'll get on it as soon
as I get back!

On Tue, 2 Jan 2024, 10:12 Niklas Gustafsson, ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> Also, please add a few unit tests.
> ------------------------------
>
> In src/TorchSharp/Functional.cs
> <https://github.com/dotnet/TorchSharp/pull/1195#discussion_r1439596950>:
>
> > +                ///  [[0, 0],
> +                ///   [1, 5]]]
> +                /// And jacobian[1]:
> +                /// [[1, 3],
> +                ///  [2, 4]]
> +                ///
> +                /// </summary>
> +                /// <param name="function">The function to compute the jacobian for. It may have multiple inputs and multiple outputs.</param>
> +                /// <param name="inputs">The values for the inputs at which to compute the jacobian.</param>
> +                /// <returns>A list of tensors, one for each output value of each output. For example, a single output with two elements yields two jacobian tensors.</returns>
> +                public static IEnumerable<Tensor> jacobian(Func<Tensor[], Tensor[]> function, params Tensor[] inputs)
> +                {
> +                    List<Tensor> jacobians = new List<Tensor>();
> +                    using (enable_grad())
> +                    {
> +                        inputs = _grad_preprocess(need_graph: true, inputs);
>
> It may be worth having a dispose scope around the body of this method.
> ------------------------------
>
> In src/TorchSharp/Functional.cs
> <https://github.com/dotnet/TorchSharp/pull/1195#discussion_r1439598779>:
>
> > +                /// var jacobian = torch.autograd.functional.jacobian(jacFunc, x1, intercepts);
> +                ///
> +                /// jacobian[0] should be:
> +                /// [[[1, 5],
> +                ///   [0, 0]],
> +                ///  [[0, 0],
> +                ///   [1, 5]]]
> +                /// And jacobian[1]:
> +                /// [[1, 3],
> +                ///  [2, 4]]
> +                ///
> +                /// </summary>
> +                /// <param name="function">The function to compute the jacobian for. It may have multiple inputs and multiple outputs.</param>
> +                /// <param name="inputs">The values for the inputs at which to compute the jacobian.</param>
> +                /// <returns>A list of tensors, one for each output value of each output. For example, a single output with two elements yields two jacobian tensors.</returns>
> +                public static IEnumerable<Tensor> jacobian(Func<Tensor[], Tensor[]> function, params Tensor[] inputs)
>
> This is very general, but consider whether there are other overloads that
> would be useful here.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/dotnet/TorchSharp/pull/1195#pullrequestreview-1800660296>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABA4LUQN4ILMXMS7KHFWER3YMQWXLAVCNFSM6AAAAABBAXNZIGVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTQMBQGY3DAMRZGY>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-01-23 10:38 UTC, roelofsmn commented
I'm getting an error when building the solution:

```
Calling "...\TorchSharp\src\Native\\gen-buildsys-win.bat" "...\TorchSharp\src\Native\" "17 2022" x64
  "C:\Program Files\CMake\bin\cmake.exe" "-DCMAKE_BUILD_TYPE=Debug" "-DCMAKE_INSTALL_PREFIX=.../TorchSharp/src/Native/../../bin/x64.Debug/Native" "-DLIBTORCH_PATH=...\TorchSharp\bin/obj/AnyCPU.Debug\libtorch-cpu\libtorch-win-shared-with-deps-debug-2.1.0cpu\libtorch\share\cmake\Torch" -G "Visual St
  udio 17 2022"  -A x64 -B. -H"...\TorchSharp\src\Native\"
  CMake Warning (dev) in CMakeLists.txt:
  -- Configuring incomplete, errors occurred!
  Failed to generate native component build project!
    No project() command is present.  The top-level CMakeLists.txt file must
    contain a literal, direct call to the project() command.  Add a line of
    code such as

      project(ProjectName)

    near the top of the file, but after cmake_minimum_required().

    CMake is pretending there is a "project(Project)" command on the first
    line.
  This warning is for project developers.  Use -Wno-dev to suppress it.

  CMake Warning (dev) in CMakeLists.txt:
    cmake_minimum_required() should be called prior to this top-level project()
    call.  Please see the cmake-commands(7) manual for usage documentation of
    both commands.
  This warning is for project developers.  Use -Wno-dev to suppress it.

  CMake Error in CMakeLists.txt:
    Generator

      Visual Studio 17 2022

    could not find any instance of Visual Studio.



...\TorchSharp\src\Native\build.proj(53,5): error MSB3073: The command ""...\TorchSharp\src\Native\build.cmd" Debug x64 --libtorchpath ...\TorchSharp\bin/obj/AnyCPU.Debug\libtorch-cpu\libtorch-win-shared-with-deps-debug-2.1.0cpu\libtorch\share\cmake\Torch" exited with code
1.

Build FAILED.

...\TorchSharp\src\Native\build.proj(53,5): error MSB3073: The command ""...\TorchSharp\src\Native\build.cmd" Debug x64 --libtorchpath ...\TorchSharp\bin/obj/AnyCPU.Debug\libtorch-cpu\libtorch-win-shared-with-deps-debug-2.1.0cpu\libtorch\share\cmake\Torch" exited with code
1.
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:45.15
```
Do you have an idea of the problem?

I'm on Windows 10, with Visual Studio 2022 17.7.0

2024-01-23 16:54 UTC, NiklasGustafsson commented
Hmm, I don't know. I would start by cleaning up the build environment, start afresh with only files from your repo:

```
git clean -xfd .
```

2024-01-25 15:21 UTC, NiklasGustafsson requested changes
This looks good to me. One thing that needs to be fixed is that there are two test projects, one that includes CUDA binaries when running locally. Since you added a new file, you need to add it to the other test project, too, with "Add as Link".

2024-01-26 17:45 UTC, merged