Include MultiheadAttention module in C# API
dotnet/TorchSharp pull request #320
Opened 2021-08-04 11:15 UTC by fwaris

We need the MultiheadAttention module by itself for some types of models. 

Although MultiheadAttention is part of the transformer modules, it is also needed separately (i.e. outside of transformer) for some models.

2021-08-04 19:07 UTC, GeorgeS2019 commented
It seems TorchSharp[ TorchText is now making critical progress.](https://github.com/xamarin/TorchSharp/issues/257#issue-892759118)

2021-08-04 19:14 UTC, GeorgeS2019 commented
@fwaris is there a plan to include unit tests and examples for MultiHeadAttention?

2021-08-04 20:58 UTC, fwaris commented
I have a unit test that is passing. It exercises the basic functionality.

I am working on porting the [Temporal Graph Network]( https://github.com/twitter-research/tgn) model which requires MHA. Once done, I can create an example also.

2021-08-10 14:56 UTC, NiklasGustafsson commented on src/TorchSharp/NN/MultiheadAttention.cs
> +                if (res1 == IntPtr.Zero) { torch.CheckForErrors(); }
I think it should probably check booth res1 and res2, just to be safe.

2021-08-10 14:57 UTC, NiklasGustafsson commented on src/TorchSharp/NN/MultiheadAttention.cs
> +            static public MultiheadAttention MultiheadAttention(long embeded_dim, long num_heads, double dropout = 0.0, bool bias = true, bool add_bias_kv = false, bool add_zero_attn = false, long? k
'embeded_dim' -> 'embedded_dim'

2021-08-10 15:52 UTC, fwaris commented on src/TorchSharp/NN/MultiheadAttention.cs
> +            static public MultiheadAttention MultiheadAttention(long embeded_dim, long num_heads, double dropout = 0.0, bool bias = true, bool add_bias_kv = false, bool add_zero_attn = false, long? k
will fix. thanks

2021-08-10 19:20 UTC, NiklasGustafsson commented
@fwaris:

This is a good addition to TorchSharp, and we really value your contribution. 

We're in the middle of moving this repository to a different organization (Xamarin is not the right long-term place for it), where we will have a proper Contributor License Agreement for all contributions, internal and external.

Therefore, we will hold off on merging this PR for a little bit.

2021-08-30 17:49 UTC, NiklasGustafsson commented
An update: this repo will be moved to the .NET Foundation organization, after which we will have the CLA and can accept the contribution.

2021-09-01 20:36 UTC, NiklasGustafsson commented
@fwaris, the easiest thing is for me to close this PR and you to open a new one. We really appreciate your contribution, and I apologize if this is inconvenient for you.

2021-09-01 21:35 UTC, dnfadmin commented
[![CLA assistant check](https://cla.dotnetfoundation.org/pull/badge/not_signed)](https://cla.dotnetfoundation.org/dotnet/TorchSharp?pullRequest=320) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/TorchSharp?pullRequest=320) before we can accept your contribution.<br/><br/>:x: fwaris [sign now](https://cla.dotnetfoundation.org/dotnet/TorchSharp?pullRequest=320)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/TorchSharp?pullRequest=320) it.</sub>

2021-09-01 21:42 UTC, NiklasGustafsson requested changes
Minor changes required before the PR will be accepted.

2021-09-01 21:42 UTC, NiklasGustafsson commented on src/TorchSharp/NN/MultiheadAttention.cs
> +// Copyright (c) Microsoft Corporation and contributors.  All Rights Reserved.  See License.txt in the project root for license information.
This should now say 'Copyright (c) .NET Foundation and Contributors. All Rights Reserved. See LICENSE in the project root for license information.'

2021-09-01 21:42 UTC, NiklasGustafsson commented on src/TorchSharp/NN/MultiheadAttention.cs
> +            //const NNModule module, const Tensor query, const Tensor key, const Tensor value, const Tensor key_padding_mask, const bool need_weights, const Tensor attn_mask, Tensor res1, Tensor res2
There's commented code,

2021-09-01 21:42 UTC, NiklasGustafsson commented on src/TorchSharp/NN/MultiheadAttention.cs
> +                //var res1 = IntPtr.Zero;
More commented code.

2021-09-01 21:42 UTC, NiklasGustafsson commented on .gitignore
> +/src/Native/out/build/x64-Debug
Odd. Was this necessary?

2021-09-01 21:42 UTC, fwaris commented
i signed the CLA but not sure if the PR is still valid. If not,  create a new one later this week.

2021-09-01 21:44 UTC, NiklasGustafsson commented
> i signed the CLA but not sure if the PR is still valid. If not, create a new one later this week.

I closed and resubmitted the PR, so now the checks are running. I had some review comments.

2021-09-02 13:56 UTC, NiklasGustafsson commented
@fwaris, I would like to get this in and then do a NuGet release with it, so I'm going to merge the PR and address the requested changes in another PR.

2021-09-02 13:56 UTC, merged

2021-09-02 14:43 UTC, fwaris commented
thanks. I will rebase and make the request changes as another PR

2021-09-02 14:45 UTC, NiklasGustafsson commented
> thanks. I will rebase and make the request changes as another PR

@fwaris, there's no need. I already made the changes and they are in main now.

2021-09-28 19:03 UTC, GeorgeS2019 commented
@fwaris  We are attempting [to visualize MultiheadAttention  module](https://github.com/fel88/Dagre.NET/issues/2) within the transformer architecture. You input is appreciated.

:-)  I still looking forwards to your tests and samples on MultiheadAttention :-)

2021-09-30 10:16 UTC, fwaris commented
day job is keeping me very busy but I intend to complete the TGN model port (see above) port in the next few weeks. Only a few modules left to port.

2021-09-30 11:32 UTC, GeorgeS2019 commented
@fwaris take your time. Thx for valuable voluntary contribution :-)